### ISSUE TITLE
Not able to get startdate and untildate 

### ISSUE THREAD

**Issue by ggarg2** [apaajabolehd/react-native-range-datepicker#2]
<DatepickerRange
							startDate= {this.props.startDate}
							untilDate= {this.props.endDate}
							dayHeadings= {['S', 'M', 'T', 'W', 'T', 'F', 'S']}
							maxMonth= {12}
							buttonColor= 'green'
							showReset= {true}
							showClose= {true}
							onClose= {this.props.toggleModal}
							onConfirm= {({startDate, untilDate}) => console.log("dates are ", startDate)}
							placeHolderStart= 'Check-in Date'
							placeHolderUntil= 'Check-out Date'
							selectedBackgroundColor= 'green'
							selectedTextColor= 'white'
							todayColor= 'green'
						/>

this statement is logging when i am selecting date ==>  'dates are ', undefined.

Any Suggestions ?

**Comment by ggarg2** [comment]
I got an answer. Remove curly braces because handleConfirmDate method is passing two parameters in onConfirm.
handleConfirmDate(){
		this.props.onConfirm && this.props.onConfirm(this.state.startDate,this.state.untilDate);
	}

Instead of using 
onConfirm= {({startDate, untilDate}) => console.log("dates are ", startDate)}

use
onConfirm= {(startDate, untilDate) => console.log("dates are ", startDate)}

@apaajabolehd please update readme

**Comment by apaajabolehd** [comment]
Thank you for figuring that out @ggarg2. I'll fix it immediately.
