### ISSUE TITLE
Better List Views in React Native

### ISSUE THREAD

**Issue by chenly** [apaajabolehd/react-native-range-datepicker#21]
https://facebook.github.io/react-native/blog/2017/03/13/better-list-views.html

**Comment by mboettcher** [comment]
created a pull request for RN 0.6 compatibility https://github.com/apaajabolehd/react-native-range-datepicker/pull/22

**Comment by johanjmoncada** [comment]
Hi, I need that PR to be merged 😬

It would allow me to use `react-native-range-datepicker` on my app 💃 

thanks @mboettcher for doing it 👍

**Comment by apaajabolehd** [comment]
merged, thank you for the update @mboettcher
