### ISSUE TITLE
One Enhancement(Select single date)

### ISSUE THREAD

**Issue by ggarg2** [apaajabolehd/react-native-range-datepicker#3]
Hi,

I am working on one user story in which i have a requirement of Date Range and Single Date. If you can target single date also then it will be very helpful.

Thanks :)

**Comment by apaajabolehd** [comment]
ok i'll try to add this feature next weekend, or if you want to add it by yourself, pull requests are welcome.

**Comment by apaajabolehd** [comment]
singledatepicker now available. Please check the new version. thx
